# From: https://hextantstudios.com/blender-addon-creation-github/

name: Build Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}

      - name: Zip Repository
        run: |
          zip -r straighten_uv_island.zip \
            ${{ github.event.repository.name }} \
            -x "${{ github.event.repository.name }}/.git*" "${{ github.event.repository.name }}/.github*" \*.md \*.png
      
      - name: Create versioned build
        run: |
          cd ${{ github.event.repository.name }}
          gh release create ${{github.ref_name}} --generate-notes \
            ../straighten_uv_island.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
